entry: gh-start
executions:
  - src:
      node: gh-start
      port: exec-on-push
    dst:
      node: gh-checkout
      port: exec
  - src:
      node: gh-checkout
      port: exec
    dst:
      node: run-v1-kangaroo-apple-tiger
      port: exec
connections: []
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: 100
      y: 100
    settings:
      folded: false
  - id: gh-checkout
    type: github.com/actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    position:
      x: 640
      y: 480
    settings:
      folded: false
  - id: run-v1-kangaroo-apple-tiger
    type: run@v1
    position:
      x: 1220
      y: 440
    inputs:
      shell: python
      script: ''
    settings:
      folded: false
registries: []
description: ''
